name: hetflow
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.9.0
  - pip=23.0.1
  - pip:
    - --find-links https://download.pytorch.org/whl/cu118
    - torch==2.0.1
    - torchaudio==2.0.2
    - torchvision==0.15.2
    - rdkit==2022.9.5
    - rdkit-pypi==2022.9.5
    - orderedset==2.0.3
    - networkx==3.1
    - scipy==1.10.1
    - seaborn==0.12.2
    - cairosvg==2.7.0
    - pandas==2.0.1
    - matplotlib==3.7.1
    - tabulate==0.9.0
    - tqdm==4.65.0
    - wandb==0.15.5
    - fcd-torch==1.0.7
    - Ipython
    